export default {
  AGE_GROUP: 'AgeGroup',
  ASSOCIATION: 'Association',
  ATHLETE: 'Athlete',
  ATHLETE_RESULT: 'AthleteResult',
  ATTEMPT: 'Attempt',
  CLUB: 'Club',
  CLUB_MEMBER: 'ClubMember',
  COMBINED_DISCIPLINE: 'CombinedDiscipline',
  COMBINED_RESULT: 'CombinedResult',
  DISCIPLINE: 'Discipline',
  EVENT: 'Event',
  GROUP: 'Group',
  HEIGHT: 'Height',
  HEIGHT_RESULT: 'HeightResult',
  MEETING: 'Meeting',
  ROUND: 'Round',
  SPLIT_TIME: 'SplitTime',
  TEAM_MEMBER: 'TeamMember',
  TEAM_RESULT: 'TeamResult',
  VENUE: 'Venue',
  I_RESULT: 'ResultInterface',
  I_ATHLETE_RESULT: 'AthleteResultInterface',
};
